config/routes.rb
Rails.application.routes.draw do

  # rails routes
  devise_for :users
  resources :pins do
    resources :comments
    member do
      put "like", to: "pins#upvote"
    end
  end

  # custom
  get '/mypage' => 'pins#mypage'
    root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pin
  belongs_to :user
end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_attached_file :image, styles: { medium: "300x300>", big: "900x900>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins,    dependent: :destroy
  has_many :comments

  validates :nickname, uniqueness: {case_sensitive: false}, presence: true, presence: true, length: {maximum: 20}
  validates :email, uniqueness: {case_sensitive: false}, presence: true, presence: true, length: {maximum: 30}

  has_attached_file :image, styles: { medium: "500x500>", big: "900x900>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image, :nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:image, :nickname])
    # devise_parameter_sanitizer.permit(:account_update, keys: [:image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @pin = Pin.find(params[:pin_id])
    @comment = @pin.comments.create(params[:comment].permit(:description))
    @comment.user_id = current_user.id
    @comment.user_email = current_user.email
    @comment.user_nickname = current_user.nickname

    if @comment.save
      redirect_to pin_path(@pin)
    else
      redirect_to :back
    end
  end

  def destroy
    @pin =  Pin.find(params[:pin_id])
    @comment = @pin.comments.find(params[:id])
    @comment.destroy

    redirect_to pin_path(@pin)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  # Read
  def index
    @pins = Pin.all.order('created_at DESC')
  end
  def show

  end

  def new
    @pin = current_user.pins.build
  end

  # Create
  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Successfully created new Pin"
    else
      render 'new'
    end
  end

  # Update
  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was Successfully updated!"
    else
      render 'edit'
    end
  end

  # Destroy
  def destroy
      @pin.destroy

      redirect_to root_path, notice: "Pin was Successfully deleted"
  end

  # like
  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

  def mypage
      @user = current_user
  end


  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
  .comment_content
    %p.comment_name
      %strong
      = comment.user_nickname
    %p.comment_body
      = comment.description
    %p.comment_time
      = time_ago_in_words(comment.created_at)
      &nbsp Ago
  -if user_signed_in?
    - if comment.user_id == current_user.id
      %p
        = link_to 'Delete', [comment.pin, comment], method: :delete, class: 'button', data: { confirm: 'Are you sure? '}



-# <div class="comment clearfix">
-# 	<div class="comment_content">
-# 		<p class="comment_name"><strong><%= comment.name %></strong></p>
-# 		<p class="comment_body"><%= comment.body %></p>
-# 		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
-# 	</div>
-#
-# 	<% if user_signed_in? %>
-# 	  <p>
-# 	    <%= link_to 'Delete', [comment.post, comment],
-# 	                  method: :delete,
-# 	                  class: 'button',
-# 	                  data: { confirm: 'Are you sure? '}
-# 	                  %>
-# 	  </p>
-# 	<% end %>
-# </div>

app/views/comments/_form.html.haml
= form_for([@pin, @pin.comments.build]) do |f|
  %p
    .form-group
      = f.label :description, for: "exampleFormControlTextarea1"
      %br
      = f.text_area :description, class: "form-control", id: "exampleFormControlTextarea1", rows: "3"
  %p
    = f.button :submit, class: "btn btn-primary"

-# <%= form_for([@post, @post.comments.build]) do |f| %>
-#   <p>
-#     <%= f.label :name %><br>
-#     <%= f.text_field :name %>
-#   </p>
-#   <p>
-#     <%= f.label :body %><br>
-#     <%= f.text_area :body %>
-#   </p>
-#   <p>
-#     <%= f.submit %>
-#   </p>
-# <% end %>

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Spoon_beta
  %link{crossorigin: "anonymous", href: "https://use.fontawesome.com/releases/v5.0.13/css/all.css", integrity: "sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp", rel: "stylesheet"}
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand.main-logo= link_to "Spoon", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Pin", new_pin_path
          %li= link_to "My Page", '/mypage'
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete

      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign In", new_user_session_path
          %li= link_to "Sign Up", new_user_registration_path

  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    = yield

-# <!DOCTYPE html>
-# <html>
-#   <head>
-#     <title>PinBoard</title>
-#     <%= csrf_meta_tags %>
-#
-#     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
-#     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
-#   </head>
-#
-#   <body>
-#     <%= yield %>
-#   </body>
-# </html>

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
  - if @pin.errors.any?
    #errors
      %h2
      = pluralize(@pin.errors.count, "error")
      prevented this Pin from saving
      %ul
        - @pin.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: { class: 'form-control' }
  .form-group
    = f.input :title, input_html: { class: 'form-control' }
  .form-group
    = f.input :description, input_html: { class: 'form-control' }

  = f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
  .pin_edit.row
    .panel.panel-default
      .panel-heading
        %h1 Edit Pin
      .panel-body
        = image_tag @pin.image.url(:big)
        %br
        %br
        = render 'form'

app/views/pins/index.html.haml
- if @pins.length == 0
  %p.index-nt-icon
    %i.fas.fa-exclamation-triangle.index-nt-icon
    %br
    %br
    %span.index-nt-icon-inner Nothing
- else
  #pins.transition-enabled
    - @pins.each do |pin|
      .box.panel.panel-default
        = link_to (image_tag pin.image.url), pin
        .panel-body
          %h2= link_to pin.title, pin
          %p.user
          Submitted by
          = pin.user.nickname

app/views/pins/mypage.html.haml
%div.profile-box
  %div.image
    %div.img-wrap
      = image_tag @user.image.url(:medium), class: "profile-image-show"
  %div.info
    %p
      %span E-mail
      %span= @user.email

    %p
      %span Nickname
      %span= @user.nickname
    %p
      = link_to "Edit", edit_user_registration_path, class: "btn btn-primary"

#pins.transition-enabled
  - @user.pins.each do |pin|
    .box.panel.panel-default
      = link_to (image_tag pin.image.url), pin
      .panel-body
        = link_to pin.title, pin

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 New form
      .panel-body
        = render 'form'

app/views/pins/show.html.haml
#pin_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin_image
        = image_tag @pin.image.url(:big)
      .panel-body
        %h1= @pin.title
        %p.description= @pin.description
        %p
        Submitted by
        = @pin.user.nickname

        #comments
          %h2
          = @pin.comments.count
          &nbsp Comments

          = render @pin.comments

          - if user_signed_in?
            %h3 Add a comment:
            = render "comments/form"
          - else
            %p
            = link_to "Sign In", new_user_session_path

        -# <h2><%= @post.comments.count %> Comments</h2>
        -# <%= render @post.comments %>
        -#
        -# <h3>Add a comment:</h3>
        -# <%= render "comments/form"%>

      .panel-footer
        .row
          .col-md-6
            %p.user
            Submitted by
            = @pin.user.email
          .col-md-6
            .btn-group.pull-right
              = link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
                %psan.glyphicon.glyphicon-heart
                  = @pin.get_upvotes.size
              - if user_signed_in?
                - if current_user.id == @pin.user_id
                  = link_to "Edit", edit_pin_path, class: "btn btn-default"
                  = link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"